---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2023/8/15 17:31
---

local bloomKeyArray = KEYS
local expireTime = ARGV[1]
for i,v in pairs(bloomKeyArray) do
    -- milliseconds
    redis.call("PEXPIRE", v, expireTime)
end


return "true"