---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2023/8/15 17:02
---

local bloomKeyArray = KEYS
--local delKeys = ""
--local count = 0
for i, v in pairs(bloomKeyArray) do
    -- 字符串拼接(在这里不能用这种方式去删除多个键)
    --delKeys = delKeys .. v .. " "

    -- 关注是否删除成功 (有可能他自己过期后删除了)
    --count= count +1
    --local result = redis.call("DEL", v)
    --if result ~= 1 then
    --    return "false"
    --end

    --不关注是否删除成功
    redis.call("DEL", v)
end

return "true"